### ISSUE TITLE
Launcher Update will fail when there are previous, not finished installs in the folder.

### ISSUE THREAD

**Issue by Ipmake** [Ipmake/kocitylauncher#1]
When theres still a file like files-1.zip or files-2.zip in the install directory that doesn't follow the new file policy then the launcher will fail and print to the console

**Comment by ohnonick2** [comment]
```
Checking for redundant files
(node:4200) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading '1')
    at C:\Users\USER\AppData\Local\Programs\knockoutcitylauncher\resources\app.asar\build\electron.js:200:61
    at IpcMainImpl.<anonymous> (C:\Users\USERa\AppData\Local\Programs\knockoutcitylauncher\resources\app.asar\build\electron.js:208:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `Knockout City Launcher --trace-warnings ...` to show where the warning was created)
(node:4200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

```
